export const REQUEST_FETCH = 'REQUEST_FETCH';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const FETCH_INFO_SUCCESS = 'FETCH_INFO_SUCCESS';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';

export const UPDATE_LIST = 'UPDATE_LIST';
export const CLEAR_LIST = 'CLEAR_LIST';
